redCards = [
    [ 'Lemonade' ],
    [ 'Carpenters' ],
    [ 'Midnight' ],
    [ 'Haunted House' ],
    [ 'Love Letters' ],
    [ 'GI Joe' ],
    [ 'Rock Stars' ],
    [ 'Paper Route' ],
    [ 'Tightrope Walking' ],
    [ 'Pearl Earings' ],
    [ 'Cutting the Grass' ],
    [ 'Mosquito Bites' ],
    [ 'Hippopotamus' ],
    [ 'Training Wheels' ],
    [ 'Barbershop Quartets' ],
    [ 'Getting Head Lice' ],
    [ 'McDonalds' ],
    [ 'Dark Alleys' ],
    [ 'Elevators' ],
    [ 'A Dollar' ],
    [ 'Motorcycles' ],
    [ 'Inchworm' ],
    [ 'Halloween' ],
    [ 'Baseball Fields' ],
    [ 'Learning to Ski' ],
    [ 'Ham Sandwich' ],
    [ 'Zippers' ],
    [ 'Substitute Teachers' ],
    [ 'Chicken Nuggets' ],
    [ 'A Leaky Boat' ],
    [ 'LEGO Building Blocks' ],
    [ 'Globes' ],
    [ 'Mushrooms' ],
    [ 'Mountain Bikes' ],
    [ 'Grapefruit' ],
    [ 'Hamsters' ],
    [ 'Listening to Music' ],
    [ 'Pokemon' ],
    [ 'Kickball' ],
    [ 'Pillow Fights' ],
    [ 'Cell Phones' ],
    [ 'Computers' ],
    [ 'Poison Ivy' ],
    [ 'Sparklers' ],
    [ 'Hammerhead Sharks' ],
    [ 'Cherries' ],
    [ 'Water Balloons' ],
    [ 'Having a Party' ],
    [ 'A Parade' ],
    [ 'Race Car Drivers' ],
    [ 'Early Morning' ],
    [ 'Getting the Flu' ],
    [ 'Muffins' ],
    [ 'Sharp Knives' ],
    [ 'Beef Stew' ],
    [ 'Mr. Potato Head' ],
    [ 'Pretzels' ],
    [ 'Toy Poodles' ],
    [ 'Truck Drivers' ],
    [ 'The Lunchroom' ],
    [ 'The Statue of Liberty' ],
    [ 'Pencils' ],
    [ 'Flies' ],
    [ 'Spider-Man' ],
    [ 'Bingo' ],
    [ 'Kindergarten' ],
    [ 'Boy Scouts' ],
    [ 'Factories' ],
    [ 'Pierced Ears' ],
    [ 'My Family' ],
    [ 'Parachutes' ],
    [ 'Supermarkets' ],
    [ 'Bowling' ],
    [ 'Warts' ],
    [ 'Airplane' ],
    [ 'Girl Scouts' ],
    [ 'Bullfighting' ],
    [ 'Caves' ],
    [ 'Soldiers' ],
    [ 'Woolly Mammoth' ],
    [ 'Resturants' ],
    [ 'Driving a Car' ],
    [ 'School Pictures' ],
    [ 'Big Dogs' ],
    [ 'Boyfriends' ],
    [ 'Spelling Bees' ],
    [ 'Swamps' ],
    [ 'Rain Forests' ],
    [ 'Nail Polish' ],
    [ 'Grape Jelly' ],
    [ 'High Heels' ],
    [ 'A Submarine' ],
    [ 'Tacos' ],
    [ 'Flour' ],
    [ 'A Movie Theater' ],
    [ 'Blood' ],
    [ 'Dictionaries' ],
    [ 'Hitting a Home Run' ],
    [ 'Guitars' ],
    [ 'The Mall' ],
    [ 'Kisses' ],
    [ 'Egg Rolls' ],
    [ 'Buffalo' ],
    [ 'Corn Flakes' ],
    [ 'Legs' ],
    [ 'A School Dance' ],
    [ 'Frogs' ],
    [ 'Superman' ],
    [ 'Noodles' ],
    [ 'Red Roses' ],
    [ 'Beach Balls' ],
    [ 'Hospitals' ],
    [ 'Octupus' ],
    [ 'Hunters' ],
    [ 'Puppets' ],
    [ 'Starfish' ],
    [ 'Artists' ],
    [ 'The Library' ],
    [ 'Cheerleaders' ],
    [ 'Pancakes' ],
    [ 'Tomato Soup' ],
    [ 'Garbage Cans' ],
    [ 'Magic Tricks' ],
    [ 'A Swimming Pool' ],
    [ 'Pumpkins' ],
    [ 'Honey' ],
    [ 'High School' ],
    [ 'Hammers' ],
    [ 'Long Hair' ],
    [ 'Gravy' ],
    [ 'Potato Chips' ],
    [ 'Swans' ],
    [ 'Flip-flops' ],
    [ 'Sand' ],
    [ 'Cupcakes' ],
    [ 'Surpise Parties' ],
    [ 'Snowflakes' ],
    [ 'Sailors' ],
    [ 'Climbing a Tree' ],
    [ 'Underwear' ],
    [ 'Vacuum Cleaners' ],
    [ 'Goats' ],
    [ 'Roosters' ],
    [ 'Woodpeckers' ],
    [ 'Zebras' ],
    [ 'On the Roof' ],
    [ 'Pimples' ],
    [ 'Black Cats' ],
    [ 'Science Experiments' ],
    [ 'A Piano' ],
    [ 'Rap Music' ],
    [ 'A Crown' ],
    [ 'Erasers' ],
    [ 'Panda Bears' ],
    [ 'A Desert' ],
    [ 'Pluto' ],
    [ 'A Cookbook' ],
    [ 'New York City' ],
    [ 'Unicorns' ],
    [ 'Niagra Falls' ],
    [ 'Dog Food' ],
    [ 'Sisters' ],
    [ 'Brothers' ],
    [ 'Backyards' ],
    [ 'Gas Stations' ],
    [ 'Helicopters' ],
    [ 'Hopscotch' ],
    [ 'Braces' ],
    [ 'Monkeys' ],
    [ 'Doughnuts' ],
    [ 'Forest Fires' ],
    [ 'Bruises' ],
    [ 'Vanila Pudding' ],
    [ 'Ketchup' ],
    [ 'Blueberries' ],
    [ 'Wrestling' ],
    [ 'Milking a Cow' ],
    [ 'Bubble Bath' ],
    [ 'Raking Leaves' ],
    [ 'Alligators' ],
    [ 'Refrigerator' ],
    [ 'The President' ],
    [ 'Strawberries' ],
    [ 'Fairies' ],
    [ 'Flags' ],
    [ 'Turkeys' ],
    [ 'Winning a Trophy' ],
    [ 'Flashlights' ],
    [ 'Losing Your Backpack' ],
    [ 'Waffles' ],
    [ 'Ballerinas' ],
    [ 'A Bakery' ],
    [ 'Girlfriends' ],
    [ 'Butterflies' ],
    [ 'Getting Lost' ],
    [ 'Meatballs' ],
    [ 'Rainbows' ],
    [ 'Ice' ],
    [ 'Bunk Beds' ],
    [ 'A Princess' ],
    [ 'Snow Boarding' ],
    [ 'Scooby-Doo' ],
    [ 'Jelly Beans' ],
    [ 'Pinocchio' ],
    [ 'Toothpaste' ],
    [ 'Burnt Toast' ],
    [ 'Thunder' ],
    [ 'Mud' ],
    [ 'Sugar' ],
    [ 'A Prince' ],
    [ 'Pinatas' ],
    [ 'Aliens' ],
    [ 'Eggs' ],
    [ 'Toasted Marshmallows' ],
    [ 'Telling Scary Stories' ],
    [ 'Lizards' ],
    [ 'Planting Flowers' ],
    [ 'Writing a Letter' ],
    [ 'Hiding Places' ],
    [ 'School Lunch' ],
    [ 'Math' ],
    [ 'Camping' ],
    [ 'Sleepovers' ],
    [ 'Hockey' ],
    [ 'Running in a Race' ],
    [ 'Doctors' ],
    [ 'Getting a Shot' ],
    [ 'Bubble Gum' ],
    [ 'Climbing a Ladder' ],
    [ 'Video Games' ],
    [ 'Collecting Shells' ],
    [ 'Skinned Knees' ],
    [ 'Brushing Your Teeth' ],
    [ 'Waterparks' ],
    [ 'Green Beans' ],
    [ 'Horses' ],
    [ 'Trees' ],
    [ 'Sneezing' ],
    [ 'Watching Cartoons' ],
    [ 'A Microwave Oven' ],
    [ 'Water Skiing' ],
    [ 'Watching Football' ],
    [ 'Clay' ],
    [ 'Rocks' ],
    [ 'Llamas' ],
    [ 'Painting a Fence' ],
    [ 'Card Games' ],
    [ 'Skateboards' ],
    [ 'Going to School' ],
    [ 'Tents' ],
    [ 'Music' ],
    [ 'Chocolate Milk' ],
    [ 'Eyes' ],
    [ 'Cookies' ],
    [ 'Rocking Chairs' ],
    [ 'Teeth' ],
    [ 'Bee Sting' ],
    [ 'Water' ],
    [ 'The Moon' ],
    [ 'Shrimp' ],
    [ 'The Earth' ],
    [ 'My Town' ],
    [ 'Mustard' ],
    [ 'My Baby Blanket' ],
    [ 'Clouds' ],
    [ 'Rain' ],
    [ 'My Best Friend' ],
    [ 'Shoppinig' ],
    [ 'Baseball Games' ],
    [ 'The Last Day of School' ],
    [ 'A Funeral' ],
    [ 'Frozen Peas' ],
    [ 'Valentine\'s Day' ],
    [ 'Coral Reef' ],
    [ 'Thanksgiving Day' ],
    [ 'Band-Aids' ],
    [ 'Science Tests' ],
    [ 'Sunken Ships' ],
    [ 'Eating Breakfast' ],
    [ 'Radios' ],
    [ 'Glass' ],
    [ 'The Ocean' ],
    [ 'Pineapples' ],
    [ 'Basketball' ],
    [ 'Getting a Haircut' ],
    [ 'Sandcastles' ],
    [ 'Volleyball' ],
    [ 'Floods' ],
    [ 'Flower Gardens' ],
    [ 'China' ],
    [ 'Ships' ],
    [ 'Bus Drivers' ],
    [ 'White Bread' ],
    [ 'Robots' ],
    [ 'Learning Spanish' ],
    [ 'Gymnastics' ],
    [ 'Taking a Shower' ],
    [ 'Africa' ],
    [ 'Belt Buckles' ],
    [ 'Mexico' ],
    [ 'Buzz Lightyear' ],
    [ 'Ears' ],
    [ 'Peacocks' ],
    [ 'Ghosts' ],
    [ 'Canoes' ],
    [ 'Carrots' ],
    [ 'Rollarblading' ],
    [ 'Tooth Fairy' ],
    [ 'Peanuts' ],
    [ 'Doorbells' ],
    [ 'Rice' ],
    [ 'Orange Juice' ],
    [ 'Skeletons' ],
    [ 'Miniature Golf' ],
    [ 'Sunburns' ],
    [ 'Pillows' ],
    [ 'Salads' ],
    [ 'Getting Stitches' ],
    [ 'Churches' ],
    [ 'A Log Cabin' ],
    [ 'Peaches' ],
    [ 'Pigs' ],
    [ 'Television' ],
    [ 'Brains' ],
    [ 'Mashed Potatoes' ],
    [ 'Pennies' ],
    [ 'Umbrellas' ],
    [ 'Bacon' ],
    [ 'Harry Potter' ],
    [ 'Dolphins' ],
    [ 'Canada' ],
    [ 'My School' ],
    [ 'Texas' ],
    [ 'Football' ],
    [ 'Tulips' ],
    [ 'Castles' ],
    [ 'Baby Food' ],
    [ 'Water Guns' ],
    [ 'Car Crash' ],
    [ 'Dirty Dishes' ],
    [ 'My Stuffed Animals' ],
    [ 'United States' ],
    [ 'Chewing Your Finger Nails' ],
    [ 'Roller Coaster' ],
    [ 'A Broken Leg' ],
    [ 'Dump Trucks' ],
    [ 'Juggling' ],
    [ 'Perfume' ],
    [ 'Surfing' ],
    [ 'Mad Scientists' ],
    [ 'Astronauts' ],
    [ 'Salt' ],
    [ 'French Fries' ],
    [ 'A Mummy' ],
    [ 'Snow Cones' ],
    [ 'Candy Corn' ],
    [ 'Bald Eagles' ],
    [ 'Grilled Cheese Sandwich' ],
    [ 'Garages' ],
    [ 'The Beach' ],
    [ 'Spinach' ],
    [ 'Rock Concerts' ],
    [ 'A Volcano' ],
    [ 'Winter' ],
    [ 'Campfire' ],
    [ 'Peppers' ],
    [ 'The Police' ],
    [ 'Going on a Safari' ],
    [ 'Music Lessons' ],
    [ 'Neighbors' ],
    [ 'My Friends' ],
    [ 'Hiking in the Woods' ],
    [ 'Farmers' ],
    [ 'Lobsters' ],
    [ 'Walking the Dog' ],
    [ 'Whipped Cream' ],
    [ 'Riding a Scooter' ],
    [ 'Rock Candy' ],
    [ 'Cooking Dinner' ],
    [ 'Dirt' ],
    [ 'Pine Cones' ],
    [ 'Cavities' ],
    [ 'Fortune Teller' ],
    [ 'Butter' ],
    [ 'Feathers' ],
    [ 'Cameras' ],
    [ 'Life Jackets' ],
    [ 'Raisins' ],
    [ 'Toenails' ],
    [ 'Sword Fighting' ],
    [ 'Hamburgers' ],
    [ 'Stomach Ache' ],
    [ 'Hot Tubs' ],
    [ 'Going on Vacation' ],
    [ 'Crying' ],
    [ 'Pickles' ],
    [ 'Power Drills' ],
    [ 'A Mermaid' ],
    [ 'Teenagers' ],
    [ 'Coffee' ],
    [ 'Dead Fish' ],
    [ 'Gorillas' ],
    [ 'The Chicken Dance' ],
    [ 'Chopsticks' ],
    [ 'Teachers' ],
    [ 'Dancing' ],
    [ 'Actors' ],
    [ 'Chicken Pox' ],
    [ 'Camels' ],
    [ 'In the Attic' ],
    [ 'Mice' ],
    [ 'Pilots' ],
    [ 'Freckles' ],
    [ 'Russia' ],
    [ 'Brazil' ],
    [ 'India' ],
    [ 'Babies' ],
    [ 'Toddlers' ],
    [ 'Pyramids of Eygpt' ],
    [ 'Cell Phones' ]
]

greenCards = [
    ["Horrible", "frightening", "awful"],
    ["Wide", "broad", "thick"],
    ["Healthy", "not sick", "well"],
    ["Gentle", "tame", "mild"],
    ["Crazy", "silly", "foolish"],
    ["Sad", "unhappy", "gloomy"],
    ["Young", "not old", "new"],
    ["Suprising", "unexpected", "amazing"],
    ["Bold", "daring", "courageous"],
    ["Rich", "wealthy", "not poor"],
    ["Friendly", "kind", "nice"],
    ["Clumsy", "awkward", "not graceful"],
    ["Proud", "dignified", "satsfied"],
    ["Sickening", "disgusting", "horrible"],
    ["Famous", "well-known", "important"],
    ["Cuddly", "cozy", "soft"],
    ["Mysterious", "strange", "sectretive"],
    ["Pale", "faded", "colorless"],
    ["Flat", "smooth", "level"],
    ["Awful", "very bad", "horrible"],
    ["Furry", "hairy", "fuzzy"],
    ["Dull", "not sharp", "plain"],
    ["Courageous", "brave", "bold"],
    ["Shy", "bashful", "timid"],
    ["Dainty", "delicate", "elegant"],
    ["Perfect", "ideal", "wonderful"],
    ["Magical", "mysterious", "delightful"],
    ["Gorgeous", "beautiful", "dazzling"],
    ["Tame", "not wild", "mild"],
    ["Crooked", "bent", "not straight"],
    ["Sneaky", "tricky", "mean"],
    ["Graceful", "elegant", "flowing"],
    ["Flavorful", "tasty", "appetizing"],
    ["Elderly", "old", "aged"],
    ["Valuable", "expensive", "important"],
    ["Calm", "peaceful", "still"],
    ["Special", "individual", "unique"],
    ["Honest", "trustworthy", "truthful"],
    ["Costly", "expensive", "valuable"],
    ["Nasty", "mean", "wicked"],
    ["Entertaining", "interesting", "fun"],
    ["Spotless", "clean", "pure"],
    ["Kind", "nice", "helpful"],
    ["Neat", "clean", "orderly"],
    ["Enjoyable", "pleasant", "fun"],
    ["Round", "circular", "ring shaped"],
    ["Playful", "fun", "cheerful"],
    ["Weak", "not strong", "sickly"],
    ["Crunchy", "crispy", "crackling"],
    ["Fearful", "scared", "worried"],
    ["Unhappy", "sad", "sorrowful"],
    ["Chewy", "gummy", "rubbery"],
    ["Fightening", "scary", "horrifying"],
    ["Excellent", "very good", "outstanding"],
    ["Painful", "hurting", "sore"],
    ["Cool", "not hot", "chilled"],
    ["Energetic", "active", "lively"],
    ["Bumpy", "lumpy", "bouncy"],
    ["Mushy", "sofy", "squishy"],
    ["Huge", "big", "large"],
    ["Fresh", "new", "clean"],
    ["Untamed", "wild", "natural"],
    ["Bright", "light", "intelligent"],
    ["Comfortable", "cozy", "pleasant"],
    ["Disgusting", "sickening", "horrible"],
    ["Chubby", "plump", "round"],
    ["Best", "greatest", "finest"],
    ["Practical", "useful", "helpful"],
    ["Sticky", "gummy", "pasty"],
    ["Loving", "caring", "kind"],
    ["Simple", "plain", "easy"],
    ["Easy", "simple", "not hard"],
    ["Serious", "important", "thoughtful"],
    ["Lucky", "fortunate", "favored"],
    ["Smart", "intelligent", "clever"],
    ["Frail", "fragile", "weak"],
    ["Terrible", "awful", "dreadful"],
    ["Quick", "fast", "speedy"],
    ["Silent", "quiet", "still"],
    ["Tough", "strong", "hard"],
    ["Delicate", "breakable", "dainty"],
    ["Attractive", "pretty", "good looking"],
    ["Worthless", "useless", "meaningless"],
    ["Difficult", "complicated", "hard"],
    ["Thick", "wide", "solid"],
    ["Dumb", "not smart", "silent"],
    ["Beautiful", "pretty", "lovely"],
    ["Expensive", "costly", "high priced"],
    ["Odd", "unusual", "strange"],
    ["Confusing", "puzzling", "weird"],
    ["Annoying", "bothersome", "irritating"],
    ["Curved", "bent", "rounded"],
    ["Useless", "worthless", "not valuable"],
    ["Careful", "cautious", "thoughtful"],
    ["Silky", "smooth", "soft"],
    ["Lazy", "slow", "careless"],
    ["Amazing", "suprising", "wonderful"],
    ["Plain", "simple", "dull"],
    ["Smelly", "stinky", "bad odor"],
    ["Ordinary", "normal", "common"],
    ["Slender", "slim", "small"],
    ["Lovable", "adorable", "enchanting"],
    ["Sporty", "athletic", "active"],
    ["Scented", "perfumed", "fragrant"],
    ["Unforgettable", "memorable", "treasured"],
    ["Interesting", "fascinating", "exciting"],
    ["Little", "small", "tiny"],
    ["Poor", "not rich", "unfortunate"],
    ["Polite", "respectful", "well mannered"],
    ["Straight", "not curved", "direct"],
    ["Charming", "pleasant", "polite"],
    ["Adorable", "lovable", "cute"],
    ["Delicious", "tasty", "pleasing"],
    ["Cheerful", "happy", "lively"],
    ["Scary", "frightening", "spooky"],
    ["Messy", "sloppy", "dirty"],
    ["Slimy", "slippery", "gooey"],
    ["Talented", "skillful", "gifted"],
    ["Pleasant", "enjoyable", "nice"],
    ["Favorite", "preferred", "desired"],
    ["Miserable", "unhappy", "sorrowful"],
    ["Peaceful", "calm", "quiet"],
    ["Busy", "active", "unavailable"],
    ["Skillful", "expert", "talented"],
    ["Fragile", "delicate", "weak"],
    ["Trustworthy", "dependable", "honest"],
    ["Harmful", "hurtful", "damaging"],
    ["Relaxed", "calm", "not tense"],
    ["Cozy", "comfortable", "warm"],
    ["Powerful", "strong", "forceful"],
    ["Enormous", "huge", "gigantic"],
    ["Fascinating", "interesting", "attractive"],
    ["Natural", "normal", "pure"],
    ["Daring", "brave", "bold"],
    ["Handy", "useful", "helpful"],
    ["Hardworking", "industrious", "active"],
    ["Caring", "concerned", "interested"],
    ["Goofy", "silly", "weird"],
    ["Thin", "skinny", "narrow"],
    ["Gigantic", "huge", "large"],
    ["Thoughtful", "caring", "unselfish"],
    ["Bitter", "sour", "tart"],
    ["Long", "not short", "stretched"],
    ["Speedy", "quick", "fast"]
]
