function _GreenCards() {
    // [word, then, list, of, synonyms]
    return [
        ["Horrible", "frightening", "awful"],
        ["Wide", "broad", "thick"],
        ["Healthy", "not sick", "well"],
        ["Gentle", "tame", "mild"],
        ["Crazy", "silly", "foolish"],
        ["Sad", "unhappy", "gloomy"],
        ["Young", "not old", "new"],
        ["Suprising", "unexpected", "amazing"],
        ["Bold", "daring", "courageous"],
        ["Rich", "wealthy", "not poor"],
        ["Friendly", "kind", "nice"],
        ["Clumsy", "awkward", "not graceful"],
        ["Proud", "dignified", "satsfied"],
        ["Sickening", "disgusting", "horrible"],
        ["Famous", "well-known", "important"],
        ["Cuddly", "cozy", "soft"],
        ["Mysterious", "strange", "sectretive"],
        ["Pale", "faded", "colorless"],
        ["Flat", "smooth", "level"],
        ["Awful", "very bad", "horrible"],
        ["Furry", "hairy", "fuzzy"],
        ["Dull", "not sharp", "plain"],
        ["Courageous", "brave", "bold"],
        ["Shy", "bashful", "timid"],
        ["Dainty", "delicate", "elegant"],
        ["Perfect", "ideal", "wonderful"],
        ["Magical", "mysterious", "delightful"],
        ["Gorgeous", "beautiful", "dazzling"],
        ["Tame", "not wild", "mild"],
        ["Crooked", "bent", "not straight"],
        ["Sneaky", "tricky", "mean"],
        ["Graceful", "elegant", "flowing"],
        ["Flavorful", "tasty", "appetizing"],
        ["Elderly", "old", "aged"],
        ["Valuable", "expensive", "important"],
        ["Calm", "peaceful", "still"],
        ["Special", "individual", "unique"],
        ["Honest", "trustworthy", "truthful"],
        ["Costly", "expensive", "valuable"],
        ["Nasty", "mean", "wicked"],
        ["Entertaining", "interesting", "fun"],
        ["Spotless", "clean", "pure"],
        ["Kind", "nice", "helpful"],
        ["Neat", "clean", "orderly"],
        ["Enjoyable", "pleasant", "fun"],
        ["Round", "circular", "ring shaped"],
        ["Playful", "fun", "cheerful"],
        ["Weak", "not strong", "sickly"],
        ["Crunchy", "crispy", "crackling"],
        ["Fearful", "scared", "worried"],
        ["Unhappy", "sad", "sorrowful"],
        ["Chewy", "gummy", "rubbery"],
        ["Fightening", "scary", "horrifying"],
        ["Excellent", "very good", "outstanding"],
        ["Painful", "hurting", "sore"],
        ["Cool", "not hot", "chilled"],
        ["Energetic", "active", "lively"],
        ["Bumpy", "lumpy", "bouncy"],
        ["Mushy", "sofy", "squishy"],
        ["Huge", "big", "large"],
        ["Fresh", "new", "clean"],
        ["Untamed", "wild", "natural"],
        ["Bright", "light", "intelligent"],
        ["Comfortable", "cozy", "pleasant"],
        ["Disgusting", "sickening", "horrible"],
        ["Chubby", "plump", "round"],
        ["Best", "greatest", "finest"],
        ["Practical", "useful", "helpful"],
        ["Sticky", "gummy", "pasty"],
        ["Loving", "caring", "kind"],
        ["Simple", "plainy", "easy"],
        ["Easy", "simple", "not hard"],
        ["Serious", "important", "thoughtful"],
        ["Lucky", "fortunate", "favored"],
        ["Smart", "intelligent", "clever"],
        ["Frail", "fragile", "weak"],
        ["Terrible", "awful", "dreadful"],
        ["Quick", "fast", "speedy"],
        ["Silent", "quiet", "still"],
        ["Tough", "strong", "hard"],
        ["Delicate", "breakable", "dainty"],
        ["Attractive", "pretty", "good looking"],
        ["Worthless", "useless", "meaningless"],
        ["Difficult", "complicated", "hard"],
        ["Thick", "wide", "solid"],
        ["Dumb", "not smart", "silent"],
        ["Beautiful", "pretty", "lovely"],
        ["Expensive", "costly", "high priced"],
        ["Odd", "unusual", "strange"],
        ["Confusing", "puzzling", "weird"],
        ["Annoying", "bothersome", "irritating"],
        ["Curved", "bent", "rounded"],
        ["Useless", "worthless", "not valuable"],
        ["Careful", "cautious", "thoughtful"],
        ["Silky", "smooth", "soft"],
        ["Lazy", "slow", "careless"],
        ["Amazing", "suprising", "wonderful"],
        ["Plain", "simple", "dull"],
        ["Smelly", "stinky", "bad odor"],
        ["Ordinary", "normal", "common"],
        ["Slender", "slim", "small"],
        ["Lovable", "adorable", "enchanting"],
        ["Sporty", "athletic", "active"],
        ["Scented", "perfumed", "fragrant"],
        ["Unforgettable", "memorable", "treasured"],
        ["Interesting", "fascinating", "exciting"],
        ["Little", "small", "tiny"],
        ["Poor", "not rich", "unfortunate"],
        ["Polite", "respectful", "well mannered"],
        ["Straight", "not curved", "direct"],
        ["Charming", "pleasant", "polite"],
        ["Adorable", "lovable", "cute"],
        ["Delicious", "tasty", "pleasing"],
        ["Cheerful", "happy", "lively"],
        ["Scary", "frightening", "spooky"],
        ["Messy", "sloppy", "dirty"],
        ["Slimy", "slippery", "gooey"],
        ["Talented", "skillful", "gifted"],
        ["Pleasant", "enjoyable", "nice"],
        ["Favorite", "preferred", "desired"],
        ["Miserable", "unhappy", "sorrowful"],
        ["Peaceful", "calm", "quiet"],
        ["Busy", "active", "unavailable"],
        ["Skillful", "expert", "talented"],
        ["Fragile", "delicate", "weak"],
        ["Trustworthy", "dependable", "honest"],
        ["Harmful", "hurtful", "damaging"],
        ["Relaxed", "calm", "not tense"],
        ["Cozy", "comfortable", "warm"],
        ["Powerful", "strong", "forceful"],
        ["Enormous", "huge", "gigantic"],
        ["Facinating", "interesting", "attractive"],
        ["Natural", "normal", "pure"],
        ["Daring", "brave", "bold"],
        ["Handy", "useful", "helpful"],
        ["Hardworking", "industrious", "active"],
        ["Caring", "concerned", "interested"],
        ["Goofy", "silly", "weird"],
        ["Thin", "skinny", "narrow"],
        ["Gigantic", "huge", "large"],
        ["Thoughtful", "caring", "unselfish"],
        ["Bitter", "sour", "tart"],
        ["Long", "not short", "stretched"],
        ["Speedy", "quick", "fast"]
    ];
}
